FROM python:3.11-slim

WORKDIR /app

# Установка необходимых пакетов
RUN apt-get update && apt-get install -y \
    git \
    curl \
    postgresql-client \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Установка poetry и зависимостей
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir poetry

# Настройка poetry
RUN poetry config virtualenvs.in-project true

# Копирование pyproject.toml для установки зависимостей
COPY pyproject.toml ./

# Установка зависимостей
RUN poetry install

# Установка pre-commit
RUN poetry run pre-commit install

# Запуск приложения в режиме разработки
CMD ["poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"] 